input {
    beats {
        # ssl => false
        port => 5044
    }
    gelf {
       host => "0.0.0.0"
       codec => "json"
       port => 12201
    }
    http { # curl -XPOST 127.0.0.1:18888 -p0 -d '{"short_message":"Hello there", "host":"example.org", "facility":"test", "_foo":"bar"}'
       ssl => false
       host => "0.0.0.0"
       port => 18888
    }
    tcp {
        # mode => "server"
        port => 50000
        # codec => line
        # codec => json
        codec => json_lines
    }
    file {
        path => "/var/lib/tomcat8/logback/*.log"
        # codec => "json"
        type => "logback"
    }
}


filter {
  mutate {
    add_field => { "source_app" => "%{[appName]}" }
  }
}

## Add your filters / logstash plugins configuration here
output {
    if [type]=="logback" {
         elasticsearch {
             hosts => [ "elasticsearch:9200" ]
             user => "logstash_internal"
             password => "${LOGSTASH_INTERNAL_PASSWORD}"
             index => "logback-%{+YYYY.MM.dd}"
        }
    }else{
        elasticsearch {
    		hosts => "elasticsearch:9200"
    		user => "logstash_internal"
    		password => "${LOGSTASH_INTERNAL_PASSWORD}"
    	}
    }
}

## Reference
# https://discuss.elastic.co/t/logstash-exposure-on-port-12201-gelf-permission-denied/200207