version: "3"
services:
  wiremock:
    image: "wiremock/wiremock:latest"
    volumes:
      - ./extensions:/var/wiremock/extensions   # gRPC extension .jar
      - ./__files:/home/wiremock/__files
      - ./mappings:/home/wiremock/mappings
    entrypoint: [ "/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose" ]
    environment:
      - JAVA_OPTS=-Dcom.github.tomakehurst.wiremock.extensions.dir=/var/wiremock/extensions
      - EXTERNAL_CODECS=snappy,another
    ports:
      - "8080:8080"
      - "8443:8443"
      - "12085:50000" # grpc port
